name: Ping Website Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Optional: lets you run it manually from UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your site
        run: |
          echo "Pinging site..."
          curl -s -o /dev/null -w "HTTP status: %{http_code}\n" https://your-site.com
